'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class MINDU_INTERMEDIAEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MINDU_INTERMEDIAEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    'Public Overridable Property EMPLE_TEMP() As DbSet(Of EmpleadoConect)

    Public Overridable Function spASISTENCIA_EMPLE_TEMPInsertar() As ObjectResult(Of spASISTENCIA_EMPLE_TEMPInsertar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spASISTENCIA_EMPLE_TEMPInsertar_Result)("spASISTENCIA_EMPLE_TEMPInsertar")
    End Function

    Public Overridable Function spASISTENCIA_EMPLE_TEMPListar() As ObjectResult(Of spASISTENCIA_EMPLE_TEMPListar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spASISTENCIA_EMPLE_TEMPListar_Result)("spASISTENCIA_EMPLE_TEMPListar")
    End Function

End Class
