'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Solicitud_HorasExtras_Colaboradores
    Public Property rut As String
    Public Property nombre_completo As String
    Public Property horas_compromiso_inicio As System.TimeSpan
    Public Property total_horas_compromiso As Double
    Public Property fecha_real As Date
    Public Property horas_efectivas_inicio As Nullable(Of System.TimeSpan)
    Public Property total_horas_efectivas As Nullable(Of Double)
    Public Property empresa As String
    Public Property cargo As String
    Public Property autorizado As Nullable(Of Boolean)
    Public Property rechazado As Nullable(Of Boolean)
    Public Property fecha_resolucion As Nullable(Of Date)
    Public Property responsable_resolucion As String
    Public Property id_solicitud_horas_extra As Integer
    Public Property Empresa_Id As String

    Public Overridable Property Solicitud_HorasExtras As Solicitud_HorasExtras

End Class
