'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ImportarExcelSQLServer.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _1491870612_icons_user2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("_1491870612_icons_user2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property abstract_user_flat_1_300px() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abstract_user_flat_1_300px", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Adelante() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Adelante", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AdelateG() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AdelateG", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ajax_loader__2_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajax_loader__2_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ajax_loader__3_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajax_loader__3_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ajax_loader__4_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajax_loader__4_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Atras() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Atras", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AtrasG() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AtrasG", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property black_male_user_symbol() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("black_male_user_symbol", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property black_ms_excel_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("black_ms_excel_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Bnt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Bnt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BntVerde() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BntVerde", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BtnDfto() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BtnDfto", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BtnDfto1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BtnDfto1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property check_mark_white_on_black_circular_background() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("check_mark_white_on_black_circular_background", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property check_mark_white_on_black_circular_background__1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("check_mark_white_on_black_circular_background__1_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property chevron_pointing_to_the_left() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("chevron_pointing_to_the_left", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property chevron_sign_left() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("chevron_sign_left", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property chevron_sign_to_right() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("chevron_sign_to_right", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property clockwise_rotation() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("clockwise_rotation", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property clockwise_rotation__1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("clockwise_rotation__1_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cooker() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cooker", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cutlery() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cutlery", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property docu_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("docu_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property file() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("file", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property foldersearch() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("foldersearch", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property foldersearchico() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("foldersearchico", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property forward_ltr() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forward_ltr", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property forward_rtl() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forward_rtl", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property forwardltr() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forwardltr", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property forwardrtl() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forwardrtl", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property goldforward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("goldforward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property goldrewind() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("goldrewind", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property home_shape() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("home_shape", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property home_shape32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("home_shape32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Image1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Image1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property list_document_interface_symbol() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("list_document_interface_symbol", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Loader() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Loader", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Loader2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Loader2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo_Grande() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo_Grande", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo_Nombre() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo_Nombre", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Lupa() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Lupa", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Lupa2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Lupa2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property lupa3() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("lupa3", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property LupaP1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("LupaP1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property LupaP2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("LupaP2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property magifier_zoom_out() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("magifier_zoom_out", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property magnifier_zoom_in() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("magnifier_zoom_in", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property menu() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("menu", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property money_report() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("money_report", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ms_excel_white16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ms_excel_white16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property multiple_users_silhouette() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("multiple_users_silhouette", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property people_check() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("people_check", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property printer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property profile_user_white16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("profile_user_white16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property restaurant() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("restaurant", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property right_chevron() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("right_chevron", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property save_file_option() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("save_file_option", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property save_file_option__1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("save_file_option__1_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property search() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property search_white16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_white16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property search1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property settings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property user() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property user_3_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("user_3_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property User_outline_icon_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("User_outline_icon_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property User_outline_icon_icon__1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("User_outline_icon_icon__1_", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property user1() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("user1", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property user3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("user3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property users__128() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("users__128", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property users64() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("users64", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property xls_icon_3402() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("xls_icon_3402", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property xls_icon_3402_16x16() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("xls_icon_3402_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property xls_icon_3404_16x16() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("xls_icon_3404_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
End Class
