'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Solicitud_Salida
    Public Property id_solicitud_salida As Integer
    Public Property solicitante As String
    Public Property trabajador As String
    Public Property rut As String
    Public Property permiso_particular As Boolean
    Public Property permiso_comision_servicio As Boolean
    Public Property dia As Date
    Public Property hora_salida As Nullable(Of System.TimeSpan)
    Public Property total_horas As Nullable(Of Double)
    Public Property fecha_real As Nullable(Of Date)
    Public Property fecha_solicitud As Date
    Public Property empresa As String
    Public Property cargo As String
    Public Property rechazada As Nullable(Of Boolean)
    Public Property autorizada As Nullable(Of Boolean)
    Public Property dia_completo As Boolean
    Public Property tramite As String
    Public Property area As String
    Public Property fecha_resolucion As Nullable(Of Date)
    Public Property responsable_resolucion As String
    Public Property check_basetempo As Nullable(Of Boolean)
    Public Property rut_solicitante As String

End Class
